# -*- coding: utf-8 -*-
"""SendData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pJ9URKt5UYdJnjkSE-MAI9Dk5o9LVoSP
"""

import urllib
from urllib.request import urlopen
import sys
from time import sleep

apiKey = '9G6WC9LUI337F84Q'
def put_data(apiKey):

  baseURL = 'https://api.thingspeak.com/update?api_key=' + apiKey + '&field1='
  num =  0.477 * 9.8
  while True:
    if num < 1:
      delay(60)
      num = 0.477 * 9.8
    print(num)
    f = urlopen(baseURL + str(num))
    print(f)
    sleep(30)
    num-=0.1

put_data(apiKey)

